function required<T extends Element>(id: string): T {
	const element = document.getElementById(id);
	if (!element) {
		throw new Error(`Missing required element #${id}`);
	}
	return element as T;
}

export function getDom() {
	return {
		addListBtn: required<HTMLButtonElement>('add-list-btn'),
		addSmartListBtn: required<HTMLButtonElement>('add-smart-list-btn'),
		apiKeyTemplate: required<HTMLTemplateElement>('api-key-template'),
		apiKeysList: required<HTMLDivElement>('api-keys-list'),
		app: required<HTMLDivElement>('app'),
		bookmarkList: required<HTMLDivElement>('bookmark-list'),
		bookmarkTemplate: required<HTMLTemplateElement>('bookmark-item-template'),
		brandTitle: required<HTMLButtonElement>('brand-title'),
		btnAddHighlight: required<HTMLButtonElement>('btn-add-highlight'),
		btnCancelList: required<HTMLButtonElement>('btn-cancel-list'),
		btnCancelNote: required<HTMLButtonElement>('btn-cancel-note'),
		btnCancelSmartList: required<HTMLButtonElement>('btn-cancel-smart-list'),
		btnCancelTags: required<HTMLButtonElement>('btn-cancel-tags'),
		btnDeleteHighlight: required<HTMLButtonElement>('btn-delete-highlight'),
		btnEditTags: required<HTMLButtonElement>('btn-edit-tags'),
		btnLogin: required<HTMLButtonElement>('btn-login'),
		btnRegister: required<HTMLButtonElement>('btn-register'),
		btnSaveList: required<HTMLButtonElement>('btn-save-list'),
		btnSaveNote: required<HTMLButtonElement>('btn-save-note'),
		btnSaveSmartList: required<HTMLButtonElement>('btn-save-smart-list'),
		btnSaveTags: required<HTMLButtonElement>('btn-save-tags'),
		contentView: required<HTMLElement>('content-view'),
		copyNewKeyBtn: required<HTMLButtonElement>('copy-new-key-btn'),
		currentViewTitle: required<HTMLElement>('current-view-title'),
		deleteBtn: required<HTMLButtonElement>('delete-btn'),
		deleteListBtn: required<HTMLButtonElement>('delete-list-btn'),
		editListBtn: required<HTMLButtonElement>('edit-list-btn'),
		emptyState: required<HTMLElement>('empty-state'),
		fontDecreaseBtn: required<HTMLButtonElement>('font-decrease-btn'),
		fontIncreaseBtn: required<HTMLButtonElement>('font-increase-btn'),
		fontSizeValue: required<HTMLElement>('font-size-value'),
		generateKeyForm: required<HTMLFormElement>('generate-key-form'),
		highlightTooltip: required<HTMLDivElement>('highlight-tooltip'),
		inboxView: required<HTMLElement>('inbox-view'),
		listHeaderActions: required<HTMLDivElement>('list-header-actions'),
		listItemCount: required<HTMLElement>('list-item-count'),
		listModal: required<HTMLDialogElement>('list-modal'),
		listModalTitle: required<HTMLElement>('list-modal-title'),
		listNameInput: required<HTMLInputElement>('list-name-input'),
		loginModal: required<HTMLDialogElement>('login-modal'),
		loginView: required<HTMLElement>('login-view'),
		logoutBtn: required<HTMLButtonElement>('logout-btn'),
		markdownContainer: required<HTMLElement>('markdown-container'),
		mcpAccountSummary: required<HTMLDivElement>('mcp-account-summary'),
		mcpConnectionValue: required<HTMLInputElement>('mcp-endpoint-value'),
		mcpFeatureList: required<HTMLDivElement>('mcp-feature-list'),
		mcpOpenApiKeysBtn: required<HTMLButtonElement>('open-api-keys-from-mcp-btn'),
		mcpPresetClaudeValue: required<HTMLTextAreaElement>('mcp-preset-claude-value'),
		mcpPresetOpenAiValue: required<HTMLTextAreaElement>('mcp-preset-openai-value'),
		mcpPresetPanel: required<HTMLElement>('mcp-preset-panel'),
		mcpSourceBridgeField: required<HTMLLabelElement>('mcp-source-bridge-field'),
		mcpSourceBridgeUrl: required<HTMLInputElement>('mcp-source-bridge-url'),
		mcpSourceHealthList: required<HTMLDivElement>('mcp-source-health-list'),
		mcpSourceIdentifier: required<HTMLInputElement>('mcp-source-identifier'),
		mcpSourceIdentifierHelp: required<HTMLElement>('mcp-source-identifier-help'),
		mcpSourceIdentifierLabel: required<HTMLElement>('mcp-source-identifier-label'),
		mcpSourceKind: required<HTMLSelectElement>('mcp-source-kind'),
		mcpSourceKindHelp: required<HTMLElement>('mcp-source-kind-help'),
		mcpSourceName: required<HTMLInputElement>('mcp-source-name'),
		mcpSourceSubmit: required<HTMLButtonElement>('mcp-source-submit'),
		mcpSourcesList: required<HTMLDivElement>('mcp-sources-list'),
		mcpSourceForm: required<HTMLFormElement>('mcp-source-form'),
		mcpStatsGrid: required<HTMLDivElement>('mcp-stats-grid'),
		mcpToolUsageList: required<HTMLDivElement>('mcp-tool-usage-list'),
		mcpView: required<HTMLElement>('mcp-view'),
		navAll: required<HTMLButtonElement>('nav-all'),
		navInbox: required<HTMLButtonElement>('nav-inbox'),
		navMcp: required<HTMLButtonElement>('nav-mcp'),
		newKeyName: required<HTMLInputElement>('new-key-name'),
		newKeyResult: required<HTMLDivElement>('new-key-result'),
		newKeyValue: required<HTMLInputElement>('new-key-value'),
		noteInput: required<HTMLTextAreaElement>('note-input'),
		noteModal: required<HTMLDialogElement>('note-modal'),
		notificationToggle: required<HTMLInputElement>('notification-toggle'),
		openSettingsBtn: required<HTMLButtonElement>('open-settings-btn'),
		passkeyForm: required<HTMLFormElement>('passkey-form'),
		pinnedBookmarkList: required<HTMLDivElement>('pinned-bookmark-list'),
		readingHeaderContainer: required<HTMLElement>('reading-header-container'),
		searchInput: required<HTMLInputElement>('search-input'),
		setupBtn: required<HTMLButtonElement>('setup-btn'),
		setupView: required<HTMLElement>('setup-view'),
		sidebarLists: required<HTMLDivElement>('sidebar-lists'),
		sidebarSmartLists: required<HTMLDivElement>('sidebar-smart-lists'),
		sidebarTags: required<HTMLDivElement>('sidebar-tags'),
		sidebarTemplate: required<HTMLTemplateElement>('sidebar-item-template'),
		smartListModal: required<HTMLDialogElement>('smart-list-modal'),
		smartListModalTitle: required<HTMLElement>('smart-list-modal-title'),
		smartListNameInput: required<HTMLInputElement>('smart-list-name-input'),
		smartListRulesInput: required<HTMLTextAreaElement>('smart-list-rules-input'),
		statRecent: required<HTMLElement>('stat-recent'),
		statTotal: required<HTMLElement>('stat-total'),
		statsPanel: required<HTMLElement>('stats-panel'),
		settingsView: required<HTMLElement>('settings-view'),
		tagsInput: required<HTMLInputElement>('tags-input'),
		tagsModal: required<HTMLDialogElement>('tags-modal'),
		toast: required<HTMLDivElement>('toast'),
		toggleStatsBtn: required<HTMLButtonElement>('toggle-stats-btn'),
		usernameInput: required<HTMLInputElement>('username-input'),
		viewDate: required<HTMLElement>('view-date'),
		viewDomain: required<HTMLElement>('view-domain'),
		viewReadingTime: required<HTMLElement>('view-reading-time'),
		viewStatus: required<HTMLElement>('view-status'),
		viewTags: required<HTMLDivElement>('view-tags'),
		viewTitle: required<HTMLElement>('view-title'),
		viewUrl: required<HTMLAnchorElement>('view-url'),
		viewWordCount: required<HTMLElement>('view-word-count'),
	};
}
